[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "python-test"
version = "0.1.0"
requires-python = ">=3.7"

[tool.scikit-build]
cmake.minimum-version = "3.27.0"
ninja.minimum-version = "1.11"

cmake.build-type = "Release"
