name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  linux:
    name: Linux-Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: cmake -S . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build
      - uses: actions/upload-artifact@v2
        with:
          name: Linux
          path: ${{github.workspace}}/build/HelloActions

  windows:
    name: Windows-Build
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: cmake -S . -B ${{github.workspace}}/build
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - uses: actions/upload-artifact@v2
        with:
          name: Windows
          path: ${{github.workspace}}/build/${{env.BUILD_TYPE}}/HelloActions.exe
