name: Comments

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  comments:
    name: Comments
    runs-on: ubuntu-22.04
    steps:
      - name: TODO
        uses: actions/github-script@v6
        with:
          script: |
            github.paginate(github.rest.issues.listComments, {
              issue_number: 5,
              owner: context.repo.owner,
              repo: context.repo.repo,
            }).then(comments => {
              comments.forEach(comment => {
                console.log(comment);
              });
            });
