name: Shader-Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  shader_check:
    name: Shader-Check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Download glslang
        run: |
          mkdir -p "${{github.workspace}}/.glslang"
          wget -q -O "${{github.workspace}}/.glslang/glslang.zip" "https://github.com/KhronosGroup/glslang/releases/download/main-tot/glslang-main-linux-Release.zip"
          unzip "${{github.workspace}}/.glslang/glslang.zip" -d "${{github.workspace}}/.glslang"
          rm "${{github.workspace}}/.glslang/glslang.zip"
      - name: Run glslang
        run: |
          "${{github.workspace}}/.glslang/bin/glslangValidator" --version
