name: Style-Fix

on:
  issue_comment:
    types: [created, edited]

jobs:
  style_fix:
    name: Style-Fix
    # if: ${{ github.event.issue.pull_request && github.event.comment.body == '/format' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Info
        run: echo "${{ toJson(github.event) }}"
      - name: Get PR Info
        id: pr-info
        uses: actions/github-script@v6
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            core.setOutput('REPO', pr.data.head.repo.full_name);
            core.setOutput('REF', pr.data.head.ref);
