name: Test

on:
  push:
    branches: [ container ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        container: ['', 'ghcr.io/unistuttgart-visus/megamol_ci_ubuntu:master']
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
    steps:
      - name: test
        run: |
          echo 'github.workspace : ${{ github.workspace }}'
          echo "GITHUB_WORKSPACE : $GITHUB_WORKSPACE"
          echo 'runner.workspace : ${{ runner.workspace }}'
          echo "RUNNER_WORKSPACE : $RUNNER_WORKSPACE"
